"""analytics_module

Revision ID: 4e9e82e0e359
Revises: 9f7eb946efb7
Create Date: 2026-06-22 18:29:08.518725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9e82e0e359'
down_revision: Union[str, None] = '9f7eb946efb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='call_direction'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='call_status'), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_conversation_id'), 'call_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_call_logs_patient_id'), 'call_logs', ['patient_id'], unique=False)
    op.create_table('cost_breakdowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('stt_cost', sa.Float(), nullable=False),
    sa.Column('llm_cost', sa.Float(), nullable=False),
    sa.Column('tts_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_breakdowns_call_id'), 'cost_breakdowns', ['call_id'], unique=False)
    op.create_table('latency_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('stt_latency_ms', sa.Float(), nullable=True),
    sa.Column('llm_latency_ms', sa.Float(), nullable=True),
    sa.Column('tts_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latency_metrics_call_id'), 'latency_metrics', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_latency_metrics_call_id'), table_name='latency_metrics')
    op.drop_table('latency_metrics')
    op.drop_index(op.f('ix_cost_breakdowns_call_id'), table_name='cost_breakdowns')
    op.drop_table('cost_breakdowns')
    op.drop_index(op.f('ix_call_logs_patient_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_conversation_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
